# Generated by Django 4.2.25 on 2025-10-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('media', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField()),
                ('statut', models.CharField(default='Valide', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
