# Generated by Django 4.2.25 on 2025-10-24 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0002_carte_delete_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte',
            old_name='date_emission',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='carte',
            old_name='media',
            new_name='media_name',
        ),
        migrations.RenameField(
            model_name='carte',
            old_name='adresse',
            new_name='owner_address',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='carte',
            name='issued_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carte',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
