# Generated by Django 4.2.25 on 2025-10-24 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0003_rename_date_emission_carte_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='ville',
        ),
        migrations.AddField(
            model_name='carte',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carte',
            name='media_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='carte',
            name='owner_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
