# Generated by Django 4.2.25 on 2025-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0004_rename_nom_carte_name_remove_carte_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='card_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='carte',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='carte',
            name='media_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du média'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du titulaire'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='owner_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse du titulaire'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_cartes/', verbose_name='Photo du titulaire'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Carte valide ?'),
        ),
    ]
