# Generated by Django 4.2.25 on 2025-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0005_alter_carte_card_id_alter_carte_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='issued_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='media_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='owner_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cartes_photos/'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
