# Generated by Django 4.2.25 on 2025-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0006_alter_carte_expiration_date_alter_carte_issued_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='photo',
        ),
        migrations.AddField(
            model_name='carte',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='media_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='owner_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
