# Generated by Django 4.2.25 on 2025-10-24 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0008_remove_carte_photo_url_carte_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='issued_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carte',
            name='media_name',
            field=models.CharField(default='Non renseigné', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carte',
            name='name',
            field=models.CharField(default='Non renseigné', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carte',
            name='owner_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
