# Generated by Django 4.2.25 on 2025-10-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0009_carte_qr_code_alter_carte_issued_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='media_name',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
        migrations.AlterField(
            model_name='carte',
            name='name',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
    ]
