# Generated by Django 4.2.25 on 2025-10-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0010_alter_carte_media_name_alter_carte_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='role',
            field=models.CharField(choices=[('media', 'Propriétaire de média'), ('comedien', 'Comédien / Humoriste'), ('influenceur', 'Influenceur / Créateur de contenu'), ('tiktokeur', 'Tiktokeur / Vidéaste'), ('chroniqueur', 'Chroniqueur / Journaliste'), ('artiste', 'Artiste / Musicien')], default='media', max_length=30, verbose_name='Rôle ou catégorie'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='card_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de carte'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date d’expiration'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='issued_at',
            field=models.DateField(auto_now_add=True, verbose_name='Date d’émission'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='media_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du média (si applicable)'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='owner_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Carte valide'),
        ),
    ]
