# Generated by Django 4.2.25 on 2025-10-24 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0011_carte_role_alter_carte_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='card_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='issued_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carte',
            name='media_name',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
        migrations.AlterField(
            model_name='carte',
            name='name',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
        migrations.AlterField(
            model_name='carte',
            name='owner_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='role',
            field=models.CharField(choices=[('Média', 'Média'), ('Chroniqueur', 'Chroniqueur'), ('Chroniqueuse', 'Chroniqueuse'), ('Influenceur', 'Influenceur'), ('Influenceuse', 'Influenceuse'), ('Tiktokeur', 'Tiktokeur'), ('Tiktokeuse', 'Tiktokeuse'), ('Comédien', 'Comédien'), ('Comédienne', 'Comédienne'), ('Artiste', 'Artiste'), ('Réalisateur', 'Réalisateur'), ('Beatmaker', 'Beatmaker'), ('Manager', 'Manager'), ('Community Manager', 'Community Manager'), ('Directeur Artistique', 'Directeur Artistique'), ('Maquilleuse Artistique', 'Maquilleuse Artistique'), ('Maître de Cérémonie', 'Maître de Cérémonie'), ('Producteur', 'Producteur'), ('Label', 'Label')], default='Média', max_length=50),
        ),
        migrations.AlterField(
            model_name='carte',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
