# Generated by Django 4.2.25 on 2025-10-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0012_alter_carte_card_id_alter_carte_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='role',
            field=models.CharField(choices=[('Média', 'Média'), ('Chroniqueur', 'Chroniqueur'), ('Chroniqueuse', 'Chroniqueuse'), ('Influenceur', 'Influenceur'), ('Influenceuse', 'Influenceuse'), ('Tiktokeur', 'Tiktokeur'), ('Tiktokeuse', 'Tiktokeuse'), ('Comédien', 'Comédien'), ('Comédienne', 'Comédienne'), ('Artiste', 'Artiste'), ('Réalisateur', 'Réalisateur'), ('Beatmaker', 'Beatmaker'), ('Manager', 'Manager'), ('Community Manager', 'Community Manager'), ('Directeur Artistique', 'Directeur Artistique'), ('Maquilleuse Artistique', 'Maquilleuse Artistique'), ('Maître de Cérémonie', 'Maître de Cérémonie'), ('Producteur', 'Producteur'), ('Label', 'Label'), ('Commerçant', 'Commerçant'), ('Commerçante', 'Commerçante')], default='Média', max_length=50),
        ),
    ]
