# Generated by Django 4.2.25 on 2025-10-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0013_alter_carte_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carte',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
