# Generated by Django 4.2.16 on 2025-10-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0014_carte_birth_date_carte_birth_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='media_name',
        ),
        migrations.AddField(
            model_name='carte',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carte',
            name='genre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carte',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('attempt_type', models.CharField(choices=[('scan', 'Scan'), ('auth', 'Auth')], default='scan', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(null=True)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='cartes.carte')),
            ],
        ),
    ]
