# Generated by Django 4.2.16 on 2025-10-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0015_remove_carte_media_name_carte_consent_carte_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanlog',
            old_name='carte',
            new_name='card',
        ),
        migrations.RemoveField(
            model_name='scanlog',
            name='attempt_type',
        ),
        migrations.RemoveField(
            model_name='scanlog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='carte',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='carte',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carte',
            name='media_name',
            field=models.CharField(default='Non renseigné', max_length=100),
        ),
        migrations.AddField(
            model_name='carte',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='genre',
            field=models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True),
        ),
    ]
