# Generated by Django 4.2.16 on 2025-10-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0016_rename_carte_scanlog_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte',
            old_name='emergency_phone',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='carte',
            old_name='personal_phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='scanlog',
            old_name='card',
            new_name='carte',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='media_name',
        ),
        migrations.AddField(
            model_name='carte',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='attempt_type',
            field=models.CharField(choices=[('scan', 'Scan'), ('auth', 'Auth')], default='scan', max_length=10),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
