# Generated by Django 4.2.16 on 2025-10-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0017_rename_emergency_phone_carte_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte',
            old_name='emergency_contact',
            new_name='emergency_phone',
        ),
        migrations.RenameField(
            model_name='carte',
            old_name='phone_number',
            new_name='personal_phone',
        ),
    ]
