# Generated by Django 4.2.16 on 2025-11-02 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0018_rename_emergency_contact_carte_emergency_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('new_card', 'Nouvelle carte'), ('lost_card', 'Déclaration de perte'), ('issue', 'Problème / Signalement'), ('contact', 'Contact')], max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('carte_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartes.carte')),
            ],
        ),
    ]
