# Generated by Django 4.2.16 on 2025-11-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0019_carterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('doc_type', models.CharField(choices=[('CNI', 'Carte Nationale'), ('PASS', 'Passeport'), ('ACTE', 'Acte de naissance')], max_length=5)),
                ('document_file', models.FileField(upload_to='demande_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
