# Generated by Django 4.2.16 on 2025-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0020_cartedemande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartedemande',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de carte', 'verbose_name_plural': 'Demandes de cartes'},
        ),
        migrations.AddField(
            model_name='cartedemande',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cartedemande',
            name='birth_date',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='cartedemande',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='cartedemande',
            name='doc_type',
            field=models.CharField(choices=[('CNI', 'Carte Nationale'), ('PASS', 'Passeport'), ('ACTE', 'Acte de naissance')], max_length=5, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='cartedemande',
            name='document_file',
            field=models.FileField(upload_to='demande_documents/', verbose_name='Document joint'),
        ),
        migrations.AlterField(
            model_name='cartedemande',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cartedemande',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='cartedemande',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
