# Generated by Django 4.2.16 on 2025-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0021_alter_cartedemande_options_cartedemande_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartePerdue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('card_id', models.CharField(max_length=50, verbose_name='ID de la carte perdue')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traitée')], default='pending', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Carte perdue',
                'verbose_name_plural': 'Cartes perdues',
                'ordering': ['-created_at'],
            },
        ),
    ]
