# Generated by Django 4.2.16 on 2025-11-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0022_carteperdue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartePerdue',
        ),
        migrations.AddField(
            model_name='carterequest',
            name='carte_id_lost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID carte perdue'),
        ),
    ]
