# Generated by Django 4.2.16 on 2025-11-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0023_delete_carteperdue_carterequest_carte_id_lost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carterequest',
            name='carte_related',
        ),
        migrations.RemoveField(
            model_name='carterequest',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='carterequest',
            name='carte_id_lost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de carte perdue (ID)'),
        ),
        migrations.AlterField(
            model_name='carterequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
    ]
