# Generated by Django 4.2.16 on 2025-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0024_remove_carterequest_carte_related_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carterequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
